version: '3.8'

services:
  # Backend API
  backend:
    build: ./backend
    container_name: ipu_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - ENV=production
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    networks:
      - ipu_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Telegram Bot
  bot:
    build: ./bot
    container_name: ipu_bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - API_URL=http://backend:8000
      - ENV=production
      - FRONTEND_PROD_URL=https://ipu-mvp.vercel.app
      - LOG_LEVEL=INFO
    depends_on:
      backend:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    networks:
      - ipu_network

  # Backend API (только backend, без nginx)
  # Nginx будет настроен отдельно на хосте

networks:
  ipu_network:
    driver: bridge

volumes:
  logs: 